[package]
name = "rcs-to-redis"
version = "1.0.0-SNAPSHOT"
authors = ["Bernd Vogt <bernd.vogt@sourcepit.org>"]

[profile.release]
debug = 1

[dependencies]
clap = "=2.33.0"
common_failures = "=0.1.1"
failure = "=0.1.6"
libc = "=0.2.66"
thread-priority = "=0.1.1"
caps = "=0.3.4"
redis = "=0.15.1"
