[package]
name = "rcs-to-redis"
version = "0.1.0"
authors = ["Bernd Vogt <bernd.vogt@sourcepit.org>"]

[dependencies]
common_failures = "0.1.1"
failure = "0.1.6"
libc = "0.2.66"
thread-priority = "0.1.1"
caps = "0.3.4"
